version: '3.9'

services:
  postgres:
    image: postgres:16-alpine
    container_name: postgres_db
    restart: always
    ports:
      - ${POSTGRES_PORT}:5432
    volumes:
      - ./.db/init.sql:/docker-entrypoint-initdb.d/init.sql
      - ./.db/data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
